### ISSUE TITLE
Get a person's information and all their relatives information

### ISSUE THREAD

**Issue by DebbieHoltzendorff** [FamilySearch/fs-js-lite#29]
I'm following the example:

```js
fs.get('/platform/tree/persons/', {
  body: { persons: [ personData ] }
}, function(error, response){ });
```

But get:

```
Uncaught ReferenceError: personData is not defined
    at _thGetFamily (treeHintsDesc.html?code=)
    at treeHintsDesc.html?code=
    at async2.1.5.js:1
    at o (async2.1.5.js:1)
    at async2.1.5.js:1
    at async2.1.5.js:1
    at async2.1.5.js:1
    at Object.<anonymous> (async2.1.5.js:1)
    at _thProcessGeneration (treeHintsDesc.html?code=)
    at treeHintsDesc.html?code=
```

I would like to retrieve a person, all his information, his spouses, all their information, his children and all their information. Any Suggestions?

**Comment by justincy** [comment]
The error is telling you that the variable "personData" hasn't been defined. Your code is attempting to send a body with the request even though you're issuing a GET. Perhaps that's a copy-paste mistake. You likely want to remove that entire object. And if you want the data from the response you can get it at response.data. So what you probably want is this:

```js
fs.get('/platform/tree/persons/L5DK-Y4Q', function(error, response){
    var persons = response.data.persons;
});
```

Now that will return the person and all his relationships but not the other persons in those relationships. To get all persons you'll need to add the query parameter as [explained in the docs](https://familysearch.org/developers/docs/api/tree/Person_resource).

```js
fs.get('/platform/tree/persons/L5DK-Y4Q?relatives=true', function(error, response){
    var persons = response.data.persons;
});
```

**Comment by DebbieHoltzendorff** [comment]
Thank you Justin. I was having trouble understanding the documentation.
Debbie

Debbie Holtzendorff
