### ISSUE TITLE
Support for self-throttling

### ISSUE THREAD

**Issue by misbach** [FamilySearch/fs-js-lite#30]
We need a way to limit the rate at which API calls will be made. For example. I want to crawl the Family Tree, and I know my code will need to make a lot of API calls. I don't care as much how fast it takes. I just don't want to send a large burst of API calls to FamilySearch all at once.

When FamilySearch gets large sudden spikes or bursts of API traffic it causes server scale up events that can take up to 15 minutes for the servers to spin up. By that time the traffic could be over. So we incurred a cost to scale up our servers for no reason. If we can level out the API traffic bursts then the server scale up events can be minimized.

If we had a self-throttling lever of say an amount of time (1,000 milliseconds etc.) to wait before each API call is made, this would allow partner apps to "play nice" with our API and not send large bursts of requests.

**Comment by justincy** [comment]
Essentially you want to allow the developer to specify a forced minimum interval between requests. Correct? This also means only one request at a time; i.e. no parallelization when this feature is enabled. Is that okay?

**Comment by misbach** [comment]
Yes, that is correct. Thank you!
