### ISSUE TITLE
Chrome ERR_BLOCKED_BY_CLIENT with any Ad-Blocker Enabled

### ISSUE THREAD

**Issue by dovy** [FamilySearch/fs-js-lite#39]
When attempting to migrate to the new JS SDK I noticed there's an issue with authentication and ad-blockers with chrome. I narrowed it down to this list: 
https://easylist.to/easylist/easylist.txt

For whatever reason, this list is blocking requests to FamilySearch, primarily ident.familysearch.org. We're not doing anything special in the code:
```
this.client.oauthToken(this.urlParams.code, function (error, tokenResponse) {
                if (error || tokenResponse.statusCode >= 400) {
                  $rootScope.log(error || restError(tokenResponse));
                }
                that.client.setAccessToken(tokenResponse.data.access_token);
                window.location = redirect;
              });
```
https://cldup.com/8VvcJauq40.png

Any ideas here? The old SDK worked without an issue...

**Comment by justincy** [comment]
Two ideas:

1. Your redirect URL has `share` in it. That might match the blacklist. I've seen really aggressive ad blacklists that remove anything with `share` in CSS classes. Perhaps they do the same with XHR requests.

2. The redirect URL doesn't need to be in the URL. It can be in the POST body (this is what the old JS SDK appears to be doing). Maybe we need to change this line: https://github.com/FamilySearch/fs-js-lite/blob/0053a8b98cefe1fba9622ced5413785fb082619b/src/FamilySearch.js#L177

**Comment by dovy** [comment]
Confirmed, that change fixed it. Pull request made.  ;)
