### ISSUE TITLE
Logout has never really worked properly...

### ISSUE THREAD

**Issue by dovy** [FamilySearch/fs-js-lite#41]
I have tried for both SDK's now to get logout to properly function with the SDK. I call the `/platform/logout` endpoint and delete my access token. It redirects to ident.familysearch.org only to reauthenticate the existing session.

I would prefer to force a re-auth, but I can't seem to find any documentation for that. Any ideas? Here's my code block for the most recent SDK.

```
              that.client.post('/platform/logout', {
                Header: {'Authorization': 'Bearer ' + that.client.getAccessToken()},
              }, function (error, response) {
                if (that.client.handleError(error, response) == false) {
                  if (error) {
                    return reject(error);
                  }
                }
                console.log(response);
                that.client.deleteAccessToken();
                delete $rootScope.user;
                return resolve(response);
              });
```

**Comment by dovy** [comment]
In all honesty, it feels like ident.familysearch.org is not syncing with the logout endpoint on api.familysearch.org.  :-/

**Comment by misbach** [comment]
The logout endpoint is broken right now :-(

**Comment by dovy** [comment]
AHA, good to know. Thanks @misbach.
